title: Remotely True
description: Stuff with varying truth values
author: Phil Steindel
github: https://github.com/remotelytrue
about: Biochemist, data scientist, and very amateur puzzle constructor
disqus_shortname: remotelytrue-disqus-io
google_analytics: 

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: 
      link: 

share:
  twitter_username: 
  fb_appid: 

urls:
    - text: About Me
      url: /about/
    - text: Blog
      url: /blog/
    - text: Projects
      url: /projects/
    - text: Github
      url: https://github.com/remotelytrue
    - text: LinkedIn
      url: https://www.linkedin.com/in/phillip-steindel-b5a48513
    - text: XML Feed
      url: /feed.xml

future: true
url: "https://remotelytrue.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist